name: mudramitra
description: "Gujarati Sign Language Learning App for Deaf & Mutes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: 0.13.6
  fluttertoast: ^8.2.12
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.5

flutter_native_splash:
  image: assets/splash/loading.jpg
  color: "#ffffff"
  fullscreen: true
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"     # App icon image for Android and iOS

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/number/
    - assets/numberaudio/
    - assets/words/
    - assets/wordsaudio/
    - assets/quiz1/
    - assets/quiz2/
    - assets/quiz3/
    - assets/icons/
    - assets/splash/
